### ISSUE TITLE
Import playground data (on mobile devices)

### ISSUE THREAD

**Issue by ericraymond** [PedalPlayground/pedalplayground#1269]
Is the a way to load pedalplayground data into Chrome on iOS?

I don't think there's a way to access developer tools or add plugins on iPad.

Perhaps it's time to add import and export ... for all devices.

**Comment by garethstockwell** [comment]
I opened a PR which adds a first draft of a "save my board" feature, which allows the canvas to be exported from one browser session and then imported into either the same or a different session: https://github.com/PedalPlayground/pedalplayground/pull/1734

It has a few limitations (due to my crappy JS coding skills) - please see the commit message for details.
