### ISSUE TITLE
Pedal request: Hudson Electronics Broadcast Dual X Regent Sounds

### ISSUE THREAD

**Issue by GreenSky91** [PedalPlayground/pedalplayground#1779]
This is not just a separate colorway, it’s also got an added high cut knob vs the other dual Broadcasts. Not sure if that’s enough to justify a separate entry :)

![IMG_0405](https://github.com/PedalPlayground/pedalplayground/assets/132704999/b9dcf5f0-a502-4643-acd9-3d817b9baab0)
(4.69 x 3.66”, Same dimensions as other Broadcasts)

**Comment by ArislanShiva** [comment]
IMO it's not really justified.

**Comment by jfmguitarist** [comment]
It's justified... it's literally a different pedal if there's different knobs/controls... this is new limitation is already affecting me in a negative way. Ridiculously, I bought the standard version of the Friedman IR-X, because I was told the Limited Edition that I originally wanted to purchase, which literally has totally different knobs, would not be added... I won't ever do that again. And as soon as I can't accurately recreate/plan my boards on here, I will no longer have any use for it, sadly. We can all do math and plan boards based on dimensions alone... what make this project so cool and fun to use is the visual aspect. I get that the database of pedals is quite large and growing weekly.... but THIS, the dynamic visual aspect,  is the key to the uniqueness and success of this project.  That's my opinion, don't crucify me for it.
