### ISSUE TITLE
Allow entry of custom dimensions in mm (as well as inches)

### ISSUE THREAD

**Issue by ericraymond** [PedalPlayground/pedalplayground#732]
Because we're too lazy to do the unit conversions outside the great tool.

**Comment by XlosVSM** [comment]
This could also add a switch which changes between imperial and metric

**Comment by Ripley63** [comment]
I'd love seeing this

**Comment by cbserra** [comment]
I had begun working on a solution locally, but I'm not well-versed in jQuery and older JavaScript, so I'm not certain the best way to implement this. 

- Basically, I created a 'User Preferences' sidebar on the left, with 'Display Units' and 2 buttons: <kbd>inches</kbd> <kbd>millimeters</kbd>. 
- Selecting a button would write the value to `localStorage['displayUnits']`, and add an `active` CSS class state to the current units. 
- I then began modifying the Pedalboard and Pedal Pop-ups to convert the measurements from inches to millimeters if `mm.` was chosen. 
- This then also requires modifying the canvas scale multiplier. Basically, default to inches and only convert to mm if the user has chosen mm. 
- however, I would need to see about the canvas data that is stored to `localStorage`. Probably best to make sure that is always stored as inches as well, since I think the pop-up windows are generated dynamically each time the pedal board or pedal is clicked.

Any thoughts on an implementation design? jQuery Plugin? Something else?

**Comment by ericraymond** [comment]
I'd leave as much of the current code alone.  I would not change the canvas data or canvas scale.  That all stays as inches.

This should start with just an input time conversion from mm to inches.  Only the edit box for a custom pedal/pedalboard need to handle this.   I'd add a choice between the units in the edit box ... but keep the internal storage as inches.

FYI, the main use case is when a vendor reports the dimensions in mm and I add a custom pedal.  It's not a global setting, but just an easy way to input the dimensions in alternate units.  

If you need to change the canvas scale multiplier, that sounds wrong.

**Comment by cbserra** [comment]
Ah ok, I thought maybe you were hoping to see the pedal/pedalboard dimensions in millimeters, as well -- totally doable!

Here's a toggle slider, based on my original thoughts

<img width="315" alt="Screen Shot 2022-04-04 at 4 16 38 PM" src="https://user-images.githubusercontent.com/789723/161647924-de39f766-6d9f-4448-baed-3e5bc7294afb.png">

**Comment by cbserra** [comment]
@ericraymond check out my PR #895 -- I've included screenshots of the toggle switch. just awaiting the maintainers to approve or provide some feedback.
